### ISSUE TITLE
no check to ensure that the filename = $label.json

### ISSUE THREAD

**Issue by mheily** [mheily/jobd#10]
Various places assume that the filename of the job is $label.json.

Nothing actually checks to makes sure this is true.

We should be strict about this.

**Comment by sgerbino** [comment]
Considering that we have a libucl implementation and it also supports other file formats, is it wise to still restrict file extensions to *.json?

**Comment by mheily** [comment]
No longer applies; we use proper IPC now and don't rely on filename conventions.
