### ISSUE TITLE
potentially dangerous use of system()

### ISSUE THREAD

**Issue by mheily** [mheily/jobd#12]
In launchd.c, there is a potentially dangerous use of system() in the pidfile_is_stale function.

Due to privilege separation, these don't present an actual security risk at the current time, but they stick out like a sore thumb during code review.

The use of system() was a shortcut, and these should be replaced with more appropriate syscalls like mkdir() and unlink().

**Comment by kmoore134** [comment]
I would add that some of the asprintf() functions are pretty scary also, especially when it comes to making / removing directories. unlink() and whatnot would be safer.

**Comment by fredmorcos** [comment]
I'd like to also mention that abort()ing everytime some little thing goes wrong (eg, asprintf() returns an error) is potentially unsafe. The least that can be done is change these to exit(). Then the better thing to do is return error values up to the caller.

**Comment by fredmorcos** [comment]
Also these system() calls are pretty much all over launchd.c, not only in pidfile_is_stale().

**Comment by mheily** [comment]
system() has been replaced with mkdir(), and all abort() calls are replaced with exit().
