### ISSUE TITLE
systemd-daemon compatibility layer

### ISSUE THREAD

**Issue by mheily** [mheily/jobd#2]
It pains me to suggest this, but there are quite a few programs already converted to use systemd socket activation, so one easy way for launchd to take advantage of this is to implement a compatibility layer. This layer would provide the following:
- a compatible implementation of libsystemd-daemon
- the header file &lt;systemd/sd-daemon.h&gt;

Here is an example of how Apache has implemented support for systemd-daemon:

https://github.com/pquerna/httpd/compare/trunk...systemd_socket_activation

**Comment by TheDharc** [comment]
hey man.
do you really think this is a good idea? I don't think BSD should be hostage to the linux staff does, I think FreeBSD people should provide a better alternative.
thanks

**Comment by mheily** [comment]
Yeah, the more I think about it, the more risky it is that the compatibility layer would suck, or not be 100% compatible with what systemd is doing.
