### ISSUE TITLE
Compilation failed (make), with configure inside the directory vendor/libucl.

### ISSUE THREAD

**Issue by ghost** [mheily/jobd#23]
I'am working on FreeBSD 10-1 release, inside virtualbox.

When I'am doing the command make from the directory relaunchd, he goes to vendor/libucl and try the
command : configure. However the command return to me an error : 

checking for library containing regexec... none required
./configure: 13974: Syntax error: word unexpected (expecting ")")

and stop.

I have attached three files in zip
[output.zip](https://github.com/mheily/relaunchd/files/62448/output.zip)

Output from uname -a, pkg info and the configure used
for the building process.

Maybe, it's a bug.

**Comment by mheily** [comment]
Can you try installing pkgconf and  then running autogen.sh inside the libucl checkout? It's failing on this line in ./configure

```
                                PKG_CHECK_MODULES(CURL, libcurl,
```

To install pkgconf, run:

```
sudo pkg install pkgconf
```

**Comment by ghost** [comment]
The solution fix the problem.

Thank you
