### ISSUE TITLE
implement RunAtLoad

### ISSUE THREAD

**Issue by mheily** [mheily/jobd#30]
Implement this:

```
    RunAtLoad <boolean>
     This optional key is used to control whether your job is launched once at
     the time the job is loaded. The default is false.
```

The documentation leaves something to be desired, so make sure this is actually something worth doing.

**Comment by rspeed** [comment]
This is absolutely worth doing, as it's a very important key. When launchd starts it loads all of the jobs, and any job that has RunAtLoad set is subsequently started. So this differentiates jobs that start at boot/login from jobs that run on a schedule or by a listener, etc.
