### ISSUE TITLE
consolidate Program and ProgramArguments

### ISSUE THREAD

**Issue by mheily** [mheily/jobd#42]
Having both ProgramArguments and Program is a bit confusing.

Would it be better to allow Program to be a string OR an array? Then we could get rid of ProgramArguments entirely.

**Comment by dabright** [comment]
Having them separate does have the advantage of allowing one to specify a full path to a program yet have the "program name" in argv[0](e.g., for ps and use as the syslog ident) be something more user friendly.

**Comment by mheily** [comment]
It never actually worked that way; the ProgramArguments key would override the Program key. I've already consolidated these keys together in Jobd, so it uses a single Program key. The intent is to KISS and not give people two ways to specify their program.

Your suggestion about setting the program name to a more user-friendly string is a good one, so I've filed issue #79 as an RFE.
