### ISSUE TITLE
fexecve not available on all platforms

### ISSUE THREAD

**Issue by Darkshadow2** [mheily/jobd#74]
This line seems to be in many of the man pages I can find for it online:

`This function is not specified in POSIX.1-2001, and is not widely available on other systems.`

Ran into it this morning when trying to compile on OpenBSD 5.9. I can also confirm `fexecve` is not available on Mac OS X.

**Comment by mheily** [comment]
Thanks! I will put in some conditional code to use execve() instead on platforms that do not have fexecve().

**Comment by mheily** [comment]
Should be fixed in 240fd3b but I have not tried compiling it on OpenBSD.

**Comment by Darkshadow2** [comment]
Can confirm it compiles & runs on OpenBSD 5.9.  Thanks!
