### ISSUE TITLE
[question] which branch to build for the most straightforward launchd alternative?

### ISSUE THREAD

**Issue by RJVB** [mheily/jobd#94]
Apologies for posting a question in an issue tracker.

I'm working on a port of a packaging system for Mac (MacPorts) in which packages can provide launchd plists that users can opt to load. I'd like to support this feature so I'm looking for a viable implementation of a launchd "clone" rather than requiring a specific host service like `systemd`.

It is not very clear from the `jobd` documentation to what extent it will fit the bill or require considerable effort in porting the plists, but I see there are at least 2 branches that install executables with familiar names like `launchd`, `launchctl` etc.

Which branch should I be looking at?

Thanks in advance!

**Comment by mheily** [comment]
jobd abandoned the requirement to be launchd-compatible long ago, and never supported the plist file format.

Your best bet is to make a thin translator layer between the plist file format and a mature supervision daemon like Supervisor - https://pypi.org/project/supervisor/

Good luck,

- Mark

------- Original Message -------

**Comment by RJVB** [comment]
I was actually inquiring about which of the older relaunchd branches I could revive. I tried the feature-launchctl-in-c branch but couldn't get it to build on Linux.

But jobd still represents a light weight solution that already does a lot of what's required. I'd have to implement a few of the features I really need, like WatchPaths, KeepAlive or ThrottleInterval but those should be relatively straightforward without need for external dependencies.

Converting plists to json is trivial too; there are several existing solutions for that.

**Comment by mheily** [comment]
Good news: I like where you're headed with this, and I'd like to help.

I've created a new GitHub repository based on the v0.6.1 tag, which is the newest commit that preserves compatibility with launchd. I fixed some bit rot, and replaced the legacy build system with one based on CMake. I've been able to build on MacOS and Linux. I'm open to accepting pull requests for features that you need.

The new repository is available at https://github.com/mheily/relaunchd

Closing this issue. Feel free to open issues in the new "relaunchd" repository as you see fit.

Cheers,

 - Mark

**Comment by RJVB** [comment]
That's good news indeed! A bit late as I'd started to work on old fork (github:kmoore134/relaunchd) but having a CMake build system is definitely an advantage! I'll have a look, thanks!

**Comment by RJVB** [comment]
Hey.

In case you didn't notice, I forked your new project and started working on it: see github:RJVB/relaunchd-mh (the RJVB branch ^^). I'm trying to be systematic with my commits but it may already be a bit complex to start doing PRs. Maybe you can just go over my commits and see if you want to cherry-pick anything.

I did have to fix a few places that failed to compile on Linux. I also added an option to build against an installed libucl and libkqueue, plus I'm in favour of following XDG standards for resource directories. If you don't agree with that I can make that configurable too.

I haven't yet grasped too well how "plists" (for lack of a better term) are loaded. With Apple's launchd you register them once and they'll be activated after logging back in or restarting the computer. Is that supposed to happen with relaunchd too, or do you have to invoke launchctl after every reboot/login?

If the former, it is probably fine to ignore Apple's `Disabled` key, if the latter it might be necessary to do something with it. Not that I am perfectly certain what it is about on Mac; launchd doesn't seem to auto-load any plists that are not disabled without asking. Maybe the ones in /System/Library/Launch{Agents,Daemons} but for the ones in the other locations you have to load them explicitly.

**Comment by mheily** [comment]
You have found one area where relaunchd isn't finished, so the behavior doesn't match what MacOS does. My goal is to fix these issues, and I have just committed an RPC mechanism that will allow launchctl to communicate better with launchd. This will allow things like enabling/disabling/stopping/starting/kickstarting.
-------- Original Message --------
