### ISSUE TITLE
config.h - No such file or directory

### ISSUE THREAD

**Issue by calmsacibis995** [mheily/jobd#95]
I'm trying to build jobd on Ubuntu 20.04, only to get this:

/home/zerocool32/jobd/database.c:28:10: fatal error: config.h: No such file or directory

Does anyone know how to fix this? I've tried deleting the build folder and recreating it to no avail.

**Comment by mheily** [comment]
I can reproduce the error, but do not plan on fixing it because this project is no longer active. You might be interested in the project that has replaced it: https://github.com/mheily/relaunchd
